name: zeye
description: "Zeye 是一个基于 Flutter 开发的应用程序，旨在提供一个简单易用的界面，用于连接 ONVIF 兼容的 IP 摄像头，获取设备信息，并播放其 RTSP 视频流。."
publish_to: "satira"
version: 0.2.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  easy_onvif: ^3.1.3
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0 # For video rendering.
  media_kit_libs_video: ^1.0.6 # Native video dependencies.
  get: ^4.6.6
  hive: ^2.2.3 # 用于数据持久化
  hive_flutter: ^1.1.0 # 用于Flutter集成
  uuid: ^4.4.0 # 用于生成唯一ID
  screenshot: ^2.1.0 # 用于Widget截图
  permission_handler: ^11.3.1 # 用于处理权限
  path_provider: ^2.1.3 # 用于获取文件路径
  image_gallery_saver_plus: ^4.0.1 # 用于保存图片到相册

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1 # 用于生成Hive适配器
  build_runner: ^2.4.9 # 用于运行代码生成
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
